### ISSUE TITLE
Restart button not working in Tic Tac Toe

### ISSUE THREAD

**Issue by Shivam-dot-com** [Shivam-dot-com/JavaScript-Projects#1]
https://github.com/Shivam-dot-com/JavaScript-Projects/blob/main/Simple%20Games/Tic%20Tac%20Toe/script.js Go to this page to check the Code.

**Comment by gautham2k3** [comment]
you could try this 
`spaces.fill(null);`
Instead of 
` spaces.forEach((space, index) => {
        space[index] = null;
    });`

**Comment by Shivam-dot-com** [comment]
Yes Brother, Thank You for suggestion. I am a beginner, and trying to improve my coding skills.

**Comment by gautham2k3** [comment]
Welcome , same here

**Comment by Shivam-dot-com** [comment]
## Restart Button
Changed Space to Spaces in Restart Function, Issue Solved
From This
![Screenshot 2023-05-31 113221](https://github.com/Shivam-dot-com/JavaScript-Projects/assets/125046336/d5023a55-0336-40fa-bb58-e171a0e2c8c6)
To This : 
![Screenshot 2023-05-31 113235](https://github.com/Shivam-dot-com/JavaScript-Projects/assets/125046336/a005dc09-e146-4ceb-8635-ee4fff345e27)
